command:
  - "python"
  - "-m"
  - "uvicorn"
  - "app:app"
  - "--host"
  - "0.0.0.0"
  - "--port"
  - "8000"
env:
  - name: SERVING_ENDPOINT
    value: databricks-claude-sonnet-4
  - name: REFUND_CATALOG
    value: refund_decisioning
  - name: MLFLOW_EXPERIMENT_NAME
    value: /Users/himanshu.gaurav@databricks.com/refund-engine/refund-agent
  - name: DATABRICKS_WAREHOUSE_ID
    value: 2dba0d7005ff019f
  - name: GENIE_SPACE_ID
    value: 01f11a3cd49319d1adad9cd327a5147e
